import { createContext, useContext, useEffect, useMemo, useRef, useState, ReactNode } from "react";
import { supabase } from "@/integrations/supabase/client";

export type Language = "en" | "ar" | "es" | "pt" | "fr" | "it" | "de";

interface Translations {
  [key: string]: {
    en: string;
    ar: string;
    es: string;
    pt: string;
    fr: string;
    it: string;
    de: string;
  };
}

export const translations: Translations = {
  // Navigation
  "nav.about": { en: "About", ar: "حول", es: "Acerca de", pt: "Sobre", fr: "À propos", it: "Chi siamo", de: "Über" },
  "nav.services": { en: "Services", ar: "الخدمات", es: "Servicios", pt: "Serviços", fr: "Services", it: "Servizi", de: "Dienstleistungen" },
  "nav.pricing": { en: "Pricing", ar: "الأسعار", es: "Precios", pt: "Preços", fr: "Tarifs", it: "Prezzi", de: "Preise" },
  "nav.caseStudies": { en: "Case Studies", ar: "دراسات الحالة", es: "Casos de Estudio", pt: "Estudos de Caso", fr: "Études de cas", it: "Casi di studio", de: "Fallstudien" },
  "nav.portfolio": { en: "Portfolio", ar: "المحفظة", es: "Portafolio", pt: "Portfólio", fr: "Portfolio", it: "Portfolio", de: "Portfolio" },
  "nav.testimonials": { en: "Testimonials", ar: "الشهادات", es: "Testimonios", pt: "Depoimentos", fr: "Témoignages", it: "Testimonianze", de: "Referenzen" },
  "nav.faq": { en: "FAQ", ar: "الأسئلة الشائعة", es: "Preguntas Frecuentes", pt: "Perguntas Frequentes", fr: "FAQ", it: "FAQ", de: "FAQ" },
  "nav.contact": { en: "Contact", ar: "اتصل بنا", es: "Contacto", pt: "Contato", fr: "Contact", it: "Contatto", de: "Kontakt" },
  "nav.blog": { en: "Blog", ar: "المدونة", es: "Blog", pt: "Blog", fr: "Blog", it: "Blog", de: "Blog" },
  "nav.bookCall": { en: "Book a Call", ar: "احجز مكالمة", es: "Reservar Llamada", pt: "Agendar Chamada", fr: "Réserver un appel", it: "Prenota una chiamata", de: "Anruf buchen" },

  // Hero
  "hero.available": { en: "Available for new projects", ar: "متاح لمشاريع جديدة", es: "Disponible para nuevos proyectos", pt: "Disponível para novos projetos", fr: "Disponible pour de nouveaux projets", it: "Disponibile per nuovi progetti", de: "Verfügbar für neue Projekte" },
  "hero.greeting": { en: "Hi, I'm Syed Hadi", ar: "مرحباً، أنا سيد هادي", es: "Hola, soy Syed Hadi", pt: "Olá, sou Syed Hadi", fr: "Bonjour, je suis Syed Hadi", it: "Ciao, sono Syed Hadi", de: "Hallo, ich bin Syed Hadi" },
  "hero.title": { en: "Your Full Stack Local SEO Specialist", ar: "متخصص SEO المحلي الشامل", es: "Tu Especialista en SEO Local Completo", pt: "Seu Especialista em SEO Local Completo", fr: "Votre Spécialiste SEO Local Complet", it: "Il Tuo Specialista SEO Locale Completo", de: "Ihr Full-Stack Local SEO Spezialist" },
  "hero.description": { en: "I help local and service-based businesses move from low visibility to top Google rankings, converting searches into consistent leads and long-term growth.", ar: "أساعد الشركات المحلية والخدمية على الانتقال من الظهور المنخفض إلى أعلى تصنيفات Google، وتحويل عمليات البحث إلى عملاء محتملين ونمو طويل الأمد.", es: "Ayudo a empresas locales y basadas en servicios a pasar de baja visibilidad a los primeros puestos en Google, convirtiendo búsquedas en clientes potenciales y crecimiento a largo plazo.", pt: "Ajudo empresas locais e baseadas em serviços a sair da baixa visibilidade para os primeiros lugares no Google, convertendo pesquisas em leads consistentes e crescimento a longo prazo.", fr: "J'aide les entreprises locales à passer d'une faible visibilité aux premiers rangs de Google, convertissant les recherches en leads constants et en croissance à long terme.", it: "Aiuto le aziende locali a passare da bassa visibilità ai primi posti su Google, convertendo le ricerche in lead costanti e crescita a lungo termine.", de: "Ich helfe lokalen Unternehmen, von geringer Sichtbarkeit zu Top-Google-Rankings zu gelangen und Suchen in beständige Leads umzuwandeln." },
  "hero.location": { en: "Helping businesses worldwide across diverse industries and regions grow online", ar: "مساعدة الشركات في جميع أنحاء العالم عبر صناعات ومناطق متنوعة للنمو عبر الإنترنت", es: "Ayudando a empresas de todo el mundo en diversas industrias y regiones a crecer en línea", pt: "Ajudando empresas em todo o mundo em diversas indústrias e regiões a crescer online", fr: "Aider les entreprises du monde entier à se développer en ligne", it: "Aiutando le aziende di tutto il mondo a crescere online", de: "Ich helfe Unternehmen weltweit beim Online-Wachstum" },
  "hero.bookAudit": { en: "Get SEO Audit — $50", ar: "احصل على تدقيق SEO — 50$", es: "Obtener Auditoría SEO — $50", pt: "Obter Auditoria SEO — $50", fr: "Obtenir un audit SEO — 50$", it: "Ottieni Audit SEO — $50", de: "SEO-Audit erhalten — 50$" },
  "hero.auditDiscount": { en: "50% OFF — Book in 24hrs!", ar: "خصم 50% — احجز خلال 24 ساعة!", es: "50% DESCUENTO — ¡Reserva en 24hrs!", pt: "50% DESCONTO — Reserve em 24hrs!", fr: "50% RÉDUCTION — Réservez en 24h!", it: "50% SCONTO — Prenota in 24 ore!", de: "50% RABATT — Buchen Sie in 24 Std!" },
  "hero.whatsapp": { en: "WhatsApp Me", ar: "راسلني على واتساب", es: "WhatsApp", pt: "WhatsApp", fr: "WhatsApp", it: "WhatsApp", de: "WhatsApp" },
  "hero.bookConsultation": { en: "Book Consultation", ar: "احجز استشارة", es: "Reservar Consulta", pt: "Agendar Consulta", fr: "Réserver une consultation", it: "Prenota Consulenza", de: "Beratung buchen" },
  "hero.viewProjects": { en: "View Projects", ar: "عرض المشاريع", es: "Ver Proyectos", pt: "Ver Projetos", fr: "Voir les projets", it: "Vedi Progetti", de: "Projekte ansehen" },
  "hero.years": { en: "Years Experience", ar: "سنوات الخبرة", es: "Años de Experiencia", pt: "Anos de Experiência", fr: "Années d'expérience", it: "Anni di esperienza", de: "Jahre Erfahrung" },
  "hero.clients": { en: "Clients Served", ar: "عملاء تم خدمتهم", es: "Clientes Atendidos", pt: "Clientes Atendidos", fr: "Clients servis", it: "Clienti serviti", de: "Betreute Kunden" },
  "hero.traffic": { en: "Avg. Traffic Increase", ar: "متوسط زيادة الزيارات", es: "Aumento Promedio de Tráfico", pt: "Aumento Médio de Tráfego", fr: "Augmentation moyenne du trafic", it: "Aumento medio del traffico", de: "Durchschn. Traffic-Steigerung" },
  "hero.googleCertified": { en: "Google Certified", ar: "معتمد من Google", es: "Certificado por Google", pt: "Certificado pelo Google", fr: "Certifié Google", it: "Certificato Google", de: "Google-zertifiziert" },
  "hero.analyticsConsole": { en: "Analytics & Search Console", ar: "التحليلات وSearch Console", es: "Analytics y Search Console", pt: "Analytics e Search Console", fr: "Analytics et Search Console", it: "Analytics e Search Console", de: "Analytics & Search Console" },

  // Contact Form
  "contact.title": { en: "Ready to Dominate Google?", ar: "هل أنت مستعد للسيطرة على Google؟", es: "¿Listo para Dominar Google?", pt: "Pronto para Dominar o Google?", fr: "Prêt à dominer Google?", it: "Pronto a dominare Google?", de: "Bereit, Google zu dominieren?" },
  "contact.subtitle": { en: "Let's Work Together", ar: "لنعمل معاً", es: "Trabajemos Juntos", pt: "Vamos Trabalhar Juntos", fr: "Travaillons ensemble", it: "Lavoriamo insieme", de: "Lassen Sie uns zusammenarbeiten" },
  "contact.description": { en: "Get a professional SEO audit for just $50 (50% OFF if you book within 24 hours!) and discover how to outrank your competitors.", ar: "احصل على تدقيق SEO احترافي مقابل 50$ فقط (خصم 50% إذا حجزت خلال 24 ساعة!) واكتشف كيف تتفوق على منافسيك.", es: "Obtenga una auditoría SEO profesional por solo $50 (¡50% DE DESCUENTO si reserva en 24 horas!) y descubra cómo superar a sus competidores.", pt: "Obtenha uma auditoria SEO profissional por apenas $50 (50% DE DESCONTO se reservar em 24 horas!) e descubra como superar seus concorrentes.", fr: "Obtenez un audit SEO professionnel pour seulement 50$ (50% de réduction si vous réservez dans les 24 heures!) et découvrez comment surpasser vos concurrents.", it: "Ottieni un audit SEO professionale per soli $50 (50% DI SCONTO se prenoti entro 24 ore!) e scopri come superare i tuoi concorrenti.", de: "Erhalten Sie ein professionelles SEO-Audit für nur 50$ (50% RABATT bei Buchung innerhalb von 24 Stunden!) und erfahren Sie, wie Sie Ihre Konkurrenten übertreffen." },
  "contact.name": { en: "Full Name", ar: "الاسم الكامل", es: "Nombre Completo", pt: "Nome Completo", fr: "Nom complet", it: "Nome completo", de: "Vollständiger Name" },
  "contact.email": { en: "Email Address", ar: "البريد الإلكتروني", es: "Correo Electrónico", pt: "Endereço de E-mail", fr: "Adresse e-mail", it: "Indirizzo email", de: "E-Mail-Adresse" },
  "contact.phone": { en: "Phone Number", ar: "رقم الهاتف", es: "Número de Teléfono", pt: "Número de Telefone", fr: "Numéro de téléphone", it: "Numero di telefono", de: "Telefonnummer" },
  "contact.company": { en: "Company Name", ar: "اسم الشركة", es: "Nombre de la Empresa", pt: "Nome da Empresa", fr: "Nom de l'entreprise", it: "Nome dell'azienda", de: "Firmenname" },
  "contact.service": { en: "Service Interested In", ar: "الخدمة المطلوبة", es: "Servicio de Interés", pt: "Serviço de Interesse", fr: "Service intéressé", it: "Servizio di interesse", de: "Interessierter Service" },
  "contact.message": { en: "Your Message", ar: "رسالتك", es: "Tu Mensaje", pt: "Sua Mensagem", fr: "Votre message", it: "Il tuo messaggio", de: "Ihre Nachricht" },
  "contact.submit": { en: "Send Message", ar: "إرسال الرسالة", es: "Enviar Mensaje", pt: "Enviar Mensagem", fr: "Envoyer le message", it: "Invia messaggio", de: "Nachricht senden" },
  "contact.sending": { en: "Sending...", ar: "جاري الإرسال...", es: "Enviando...", pt: "Enviando...", fr: "Envoi en cours...", it: "Invio in corso...", de: "Wird gesendet..." },
  "contact.success": { en: "Message sent successfully! I'll get back to you soon.", ar: "تم إرسال الرسالة بنجاح! سأرد عليك قريباً.", es: "¡Mensaje enviado con éxito! Te responderé pronto.", pt: "Mensagem enviada com sucesso! Entrarei em contato em breve.", fr: "Message envoyé avec succès! Je vous répondrai bientôt.", it: "Messaggio inviato con successo! Ti risponderò presto.", de: "Nachricht erfolgreich gesendet! Ich melde mich bald bei Ihnen." },
  "contact.error": { en: "Failed to send message. Please try again.", ar: "فشل إرسال الرسالة. يرجى المحاولة مرة أخرى.", es: "Error al enviar el mensaje. Por favor, inténtelo de nuevo.", pt: "Falha ao enviar mensagem. Por favor, tente novamente.", fr: "Échec de l'envoi du message. Veuillez réessayer.", it: "Impossibile inviare il messaggio. Si prega di riprovare.", de: "Nachricht konnte nicht gesendet werden. Bitte versuchen Sie es erneut." },
  "contact.clientName": { en: "Client Name", ar: "اسم العميل", es: "Nombre del Cliente", pt: "Nome do Cliente", fr: "Nom du client", it: "Nome del cliente", de: "Kundenname" },
  "contact.businessName": { en: "Business Name", ar: "اسم العمل", es: "Nombre del Negocio", pt: "Nome da Empresa", fr: "Nom de l'entreprise", it: "Nome dell'azienda", de: "Firmenname" },
  "contact.businessAddress": { en: "Business Address", ar: "عنوان العمل", es: "Dirección del Negocio", pt: "Endereço da Empresa", fr: "Adresse de l'entreprise", it: "Indirizzo dell'azienda", de: "Geschäftsadresse" },
  "contact.city": { en: "City", ar: "المدينة", es: "Ciudad", pt: "Cidade", fr: "Ville", it: "Città", de: "Stadt" },
  "contact.state": { en: "State/Province", ar: "الولاية/المقاطعة", es: "Estado/Provincia", pt: "Estado/Província", fr: "État/Province", it: "Stato/Provincia", de: "Bundesland" },
  "contact.zipcode": { en: "Zipcode", ar: "الرمز البريدي", es: "Código Postal", pt: "CEP", fr: "Code postal", it: "CAP", de: "Postleitzahl" },
  "contact.country": { en: "Country", ar: "البلد", es: "País", pt: "País", fr: "Pays", it: "Paese", de: "Land" },
  "contact.selectService": { en: "Select a service", ar: "اختر خدمة", es: "Seleccione un servicio", pt: "Selecione um serviço", fr: "Sélectionnez un service", it: "Seleziona un servizio", de: "Service auswählen" },
  "contact.gbpLink": { en: "GBP/Map Link", ar: "رابط خرائط جوجل", es: "Enlace de GBP/Mapa", pt: "Link do GBP/Mapa", fr: "Lien GBP/Carte", it: "Link GBP/Mappa", de: "GBP/Karten-Link" },
  "contact.gbpLinkHint": { en: "Paste your Google Business Profile or Google Maps link", ar: "الصق رابط ملف Google التجاري أو خرائط Google", es: "Pegue su enlace de Google Business Profile o Google Maps", pt: "Cole seu link do Google Business Profile ou Google Maps", fr: "Collez votre lien Google Business Profile ou Google Maps", it: "Incolla il tuo link Google Business Profile o Google Maps", de: "Fügen Sie Ihren Google Business Profile- oder Google Maps-Link ein" },
  "contact.competitor": { en: "Competitor (Optional)", ar: "المنافس (اختياري)", es: "Competidor (Opcional)", pt: "Concorrente (Opcional)", fr: "Concurrent (Optionnel)", it: "Concorrente (Opzionale)", de: "Wettbewerber (Optional)" },
  "contact.customService": { en: "Describe Your Custom Service", ar: "صف خدمتك المخصصة", es: "Describe Tu Servicio Personalizado", pt: "Descreva Seu Serviço Personalizado", fr: "Décrivez votre service personnalisé", it: "Descrivi il tuo servizio personalizzato", de: "Beschreiben Sie Ihren benutzerdefinierten Service" },
  "contact.formGuide": { en: "Need help? Read the form guide", ar: "تحتاج مساعدة؟ اقرأ دليل النموذج", es: "¿Necesita ayuda? Lea la guía del formulario", pt: "Precisa de ajuda? Leia a guia do formulário", fr: "Besoin d'aide? Lisez le guide du formulaire", it: "Hai bisogno di aiuto? Leggi la guida al modulo", de: "Brauchen Sie Hilfe? Lesen Sie die Formularanleitung" },
  "contact.bookCall": { en: "Book a Call", ar: "احجز مكالمة", es: "Reservar Llamada", pt: "Agendar Chamada", fr: "Réserver un appel", it: "Prenota una chiamata", de: "Anruf buchen" },
  "contact.scheduleMeeting": { en: "Schedule a meeting", ar: "جدولة اجتماع", es: "Programar una reunión", pt: "Agendar reunião", fr: "Planifier une réunion", it: "Pianifica un incontro", de: "Meeting planen" },
  "contact.whatsapp": { en: "WhatsApp", ar: "واتساب", es: "WhatsApp", pt: "WhatsApp", fr: "WhatsApp", it: "WhatsApp", de: "WhatsApp" },
  "contact.quickChat": { en: "Quick chat", ar: "محادثة سريعة", es: "Chat rápido", pt: "Chat rápido", fr: "Chat rapide", it: "Chat veloce", de: "Schneller Chat" },
  "contact.worldwide": { en: "Worldwide", ar: "حول العالم", es: "Mundial", pt: "Mundial", fr: "Mondial", it: "Mondiale", de: "Weltweit" },
  "contact.sendInquiry": { en: "Send a Detailed Inquiry", ar: "أرسل استفساراً مفصلاً", es: "Enviar una Consulta Detallada", pt: "Enviar uma Consulta Detalhada", fr: "Envoyer une demande détaillée", it: "Invia una richiesta dettagliata", de: "Detaillierte Anfrage senden" },
  "contact.customServiceHint": { en: "Please describe the specific service you're looking for", ar: "يرجى وصف الخدمة المحددة التي تبحث عنها", es: "Por favor describa el servicio específico que está buscando", pt: "Por favor, descreva o serviço específico que você está procurando", fr: "Veuillez décrire le service spécifique que vous recherchez", it: "Si prega di descrivere il servizio specifico che stai cercando", de: "Bitte beschreiben Sie den spezifischen Service, den Sie suchen" },

  // Services
  "services.title": { en: "Local SEO Services That Drive Results", ar: "خدمات SEO المحلية التي تحقق النتائج", es: "Servicios de SEO Local que Generan Resultados", pt: "Serviços de SEO Local que Geram Resultados", fr: "Services SEO locaux qui génèrent des résultats", it: "Servizi SEO locali che generano risultati", de: "Lokale SEO-Dienste, die Ergebnisse liefern" },
  "services.subtitle": { en: "Comprehensive strategies to boost your local visibility", ar: "استراتيجيات شاملة لتعزيز ظهورك المحلي", es: "Estrategias integrales para impulsar tu visibilidad local", pt: "Estratégias abrangentes para aumentar sua visibilidade local", fr: "Stratégies complètes pour booster votre visibilité locale", it: "Strategie complete per aumentare la tua visibilità locale", de: "Umfassende Strategien zur Steigerung Ihrer lokalen Sichtbarkeit" },
  "services.badge": { en: "Services", ar: "الخدمات", es: "Servicios", pt: "Serviços", fr: "Services", it: "Servizi", de: "Dienstleistungen" },
  "services.heading": { en: "My Services Designed to Boost Business Growth", ar: "خدماتي المصممة لتعزيز نمو الأعمال", es: "Mis Servicios Diseñados para Impulsar el Crecimiento Empresarial", pt: "Meus Serviços Projetados para Impulsionar o Crescimento dos Negócios", fr: "Mes services conçus pour stimuler la croissance des entreprises", it: "I miei servizi progettati per aumentare la crescita aziendale", de: "Meine Dienstleistungen für Ihr Unternehmenswachstum" },
  "services.description": { en: "I provide full-stack SEO and local growth services, designed for businesses that want measurable results, AI-ready strategies, and top local map visibility.", ar: "أقدم خدمات SEO شاملة ونمو محلي، مصممة للشركات التي تريد نتائج قابلة للقياس واستراتيجيات جاهزة للذكاء الاصطناعي وأعلى ظهور على الخرائط المحلية.", es: "Proporciono servicios SEO completos y crecimiento local, diseñados para empresas que quieren resultados medibles, estrategias listas para IA y máxima visibilidad en mapas locales.", pt: "Forneço serviços completos de SEO e crescimento local, projetados para empresas que desejam resultados mensuráveis, estratégias prontas para IA e máxima visibilidade em mapas locais.", fr: "Je fournis des services SEO complets et de croissance locale, conçus pour les entreprises qui veulent des résultats mesurables, des stratégies prêtes pour l'IA et une visibilité maximale sur les cartes locales.", it: "Fornisco servizi SEO completi e crescita locale, progettati per le aziende che vogliono risultati misurabili, strategie pronte per l'IA e massima visibilità sulle mappe locali.", de: "Ich biete Full-Stack-SEO- und lokale Wachstumsdienste für Unternehmen, die messbare Ergebnisse, KI-bereite Strategien und Top-Sichtbarkeit auf lokalen Karten wollen." },

  // Service items
  "services.localSeo": { en: "Local SEO Optimization", ar: "تحسين SEO المحلي", es: "Optimización SEO Local", pt: "Otimização SEO Local", fr: "Optimisation SEO local", it: "Ottimizzazione SEO locale", de: "Lokale SEO-Optimierung" },
  "services.localSeoDesc": { en: "I boost your visibility on Google Search with local SEO strategies that attract high-intent customers in your local area.", ar: "أعزز ظهورك على بحث Google باستراتيجيات SEO محلية تجذب العملاء ذوي النية العالية في منطقتك المحلية.", es: "Impulso tu visibilidad en Google Search con estrategias SEO locales que atraen clientes de alta intención en tu área local.", pt: "Aumento sua visibilidade no Google Search com estratégias de SEO local que atraem clientes de alta intenção em sua área local.", fr: "Je booste votre visibilité sur Google Search avec des stratégies SEO locales qui attirent des clients à forte intention dans votre zone locale.", it: "Aumento la tua visibilità su Google Search con strategie SEO locali che attraggono clienti ad alta intenzione nella tua zona.", de: "Ich steigere Ihre Sichtbarkeit in der Google-Suche mit lokalen SEO-Strategien, die kaufwillige Kunden in Ihrer Region anziehen." },
  "services.gbp": { en: "Google Business Profile Management", ar: "إدارة ملف Google التجاري", es: "Gestión de Google Business Profile", pt: "Gerenciamento do Google Business Profile", fr: "Gestion de Google Business Profile", it: "Gestione Google Business Profile", de: "Google Business Profile Verwaltung" },
  "services.gbpDesc": { en: "I handle the complete setup, optimization, and management of your Google Business Profile to maximize visibility in search, maps, and AI-powered listings.", ar: "أتولى الإعداد الكامل والتحسين وإدارة ملف Google التجاري الخاص بك لتعظيم الظهور في البحث والخرائط والقوائم المدعومة بالذكاء الاصطناعي.", es: "Manejo la configuración completa, optimización y gestión de tu Google Business Profile para maximizar la visibilidad en búsqueda, mapas y listados potenciados por IA.", pt: "Cuido da configuração completa, otimização e gerenciamento do seu Google Business Profile para maximizar a visibilidade em pesquisa, mapas e listagens com IA.", fr: "Je gère la configuration complète, l'optimisation et la gestion de votre Google Business Profile pour maximiser la visibilité dans la recherche, les cartes et les listes alimentées par l'IA.", it: "Gestisco la configurazione completa, l'ottimizzazione e la gestione del tuo Google Business Profile per massimizzare la visibilità nella ricerca, mappe e elenchi alimentati dall'IA.", de: "Ich übernehme die komplette Einrichtung, Optimierung und Verwaltung Ihres Google Business Profiles für maximale Sichtbarkeit in Suche, Karten und KI-gestützten Listen." },
  "services.mapSeo": { en: "Map SEO – Google, Apple, Bing", ar: "SEO الخرائط – Google، Apple، Bing", es: "SEO de Mapas – Google, Apple, Bing", pt: "SEO de Mapas – Google, Apple, Bing", fr: "SEO Maps – Google, Apple, Bing", it: "SEO Mappe – Google, Apple, Bing", de: "Karten-SEO – Google, Apple, Bing" },
  "services.mapSeoDesc": { en: "I optimize your presence on Google Maps, Apple Maps, Bing Maps, and other location-based platforms to effectively capture local searches.", ar: "أحسن تواجدك على خرائط Google وApple وBing ومنصات أخرى قائمة على الموقع لجذب عمليات البحث المحلية بفعالية.", es: "Optimizo tu presencia en Google Maps, Apple Maps, Bing Maps y otras plataformas basadas en ubicación para capturar efectivamente búsquedas locales.", pt: "Otimizo sua presença no Google Maps, Apple Maps, Bing Maps e outras plataformas baseadas em localização para capturar efetivamente pesquisas locais.", fr: "J'optimise votre présence sur Google Maps, Apple Maps, Bing Maps et d'autres plateformes basées sur la localisation pour capturer efficacement les recherches locales.", it: "Ottimizzo la tua presenza su Google Maps, Apple Maps, Bing Maps e altre piattaforme basate sulla posizione per catturare efficacemente le ricerche locali.", de: "Ich optimiere Ihre Präsenz auf Google Maps, Apple Maps, Bing Maps und anderen standortbasierten Plattformen für effektive lokale Suchen." },
  "services.keywordResearch": { en: "Keyword Research & Semantic SEO", ar: "بحث الكلمات المفتاحية وSEO الدلالي", es: "Investigación de Palabras Clave y SEO Semántico", pt: "Pesquisa de Palavras-chave e SEO Semântico", fr: "Recherche de mots-clés et SEO sémantique", it: "Ricerca parole chiave e SEO semantico", de: "Keyword-Recherche & Semantisches SEO" },
  "services.keywordResearchDesc": { en: "I identify the best keywords for your business, including voice search and AI-generated queries, to drive relevant traffic that converts.", ar: "أحدد أفضل الكلمات المفتاحية لعملك، بما في ذلك البحث الصوتي واستعلامات الذكاء الاصطناعي، لجلب حركة مرور ذات صلة تتحول إلى عملاء.", es: "Identifico las mejores palabras clave para tu negocio, incluyendo búsqueda por voz y consultas generadas por IA, para atraer tráfico relevante que convierte.", pt: "Identifico as melhores palavras-chave para seu negócio, incluindo pesquisa por voz e consultas geradas por IA, para direcionar tráfego relevante que converte.", fr: "J'identifie les meilleurs mots-clés pour votre entreprise, y compris la recherche vocale et les requêtes générées par l'IA, pour générer un trafic pertinent qui convertit.", it: "Identifico le migliori parole chiave per la tua attività, inclusa la ricerca vocale e le query generate dall'IA, per generare traffico rilevante che converte.", de: "Ich identifiziere die besten Keywords für Ihr Unternehmen, einschließlich Sprachsuche und KI-generierte Anfragen, um relevanten Traffic zu generieren, der konvertiert." },
  "services.onPage": { en: "On-Page SEO", ar: "SEO على الصفحة", es: "SEO On-Page", pt: "SEO On-Page", fr: "SEO On-Page", it: "SEO On-Page", de: "On-Page SEO" },
  "services.onPageDesc": { en: "I optimize website pages with meta tags, headings, structured data, and semantic markup to improve rankings and relevance for search engines and AI assistants.", ar: "أحسن صفحات الموقع بالعلامات الوصفية والعناوين والبيانات المهيكلة والترميز الدلالي لتحسين الترتيب والملاءمة لمحركات البحث ومساعدي الذكاء الاصطناعي.", es: "Optimizo páginas web con meta etiquetas, encabezados, datos estructurados y marcado semántico para mejorar rankings y relevancia para motores de búsqueda y asistentes IA.", pt: "Otimizo páginas de sites com meta tags, títulos, dados estruturados e marcação semântica para melhorar rankings e relevância para mecanismos de busca e assistentes de IA.", fr: "J'optimise les pages web avec des balises meta, des en-têtes, des données structurées et un balisage sémantique pour améliorer les classements et la pertinence pour les moteurs de recherche et les assistants IA.", it: "Ottimizzo le pagine web con meta tag, intestazioni, dati strutturati e markup semantico per migliorare i ranking e la rilevanza per i motori di ricerca e gli assistenti IA.", de: "Ich optimiere Website-Seiten mit Meta-Tags, Überschriften, strukturierten Daten und semantischem Markup für bessere Rankings und Relevanz bei Suchmaschinen und KI-Assistenten." },
  "services.technical": { en: "Technical SEO", ar: "SEO التقني", es: "SEO Técnico", pt: "SEO Técnico", fr: "SEO Technique", it: "SEO Tecnico", de: "Technisches SEO" },
  "services.technicalDesc": { en: "I fix site performance, speed, mobile-friendliness, indexing, and crawl issues so your website works flawlessly for both Google and AI-powered search engines.", ar: "أصلح أداء الموقع والسرعة والتوافق مع الجوال والفهرسة ومشاكل الزحف ليعمل موقعك بشكل مثالي لـ Google ومحركات البحث المدعومة بالذكاء الاصطناعي.", es: "Soluciono rendimiento del sitio, velocidad, compatibilidad móvil, indexación y problemas de rastreo para que tu sitio funcione perfectamente para Google y motores de búsqueda con IA.", pt: "Corrijo desempenho do site, velocidade, compatibilidade móvel, indexação e problemas de rastreamento para que seu site funcione perfeitamente para Google e mecanismos de busca com IA.", fr: "Je corrige les performances du site, la vitesse, la compatibilité mobile, l'indexation et les problèmes d'exploration pour que votre site fonctionne parfaitement pour Google et les moteurs de recherche alimentés par l'IA.", it: "Risolvo prestazioni del sito, velocità, compatibilità mobile, indicizzazione e problemi di scansione affinché il tuo sito funzioni perfettamente per Google e i motori di ricerca alimentati dall'IA.", de: "Ich behebe Website-Performance, Geschwindigkeit, Mobile-Freundlichkeit, Indexierung und Crawl-Probleme, damit Ihre Website perfekt für Google und KI-gestützte Suchmaschinen funktioniert." },
  "services.content": { en: "Content Strategy & AI-Optimized Content", ar: "استراتيجية المحتوى والمحتوى المحسن للذكاء الاصطناعي", es: "Estrategia de Contenido y Contenido Optimizado para IA", pt: "Estratégia de Conteúdo e Conteúdo Otimizado para IA", fr: "Stratégie de contenu et contenu optimisé pour l'IA", it: "Strategia di contenuti e contenuti ottimizzati per l'IA", de: "Content-Strategie & KI-optimierte Inhalte" },
  "services.contentDesc": { en: "I create high-quality, AI-ready content for service pages, blogs, FAQs, and landing pages to rank on search engines, maps, and generative platforms.", ar: "أنشئ محتوى عالي الجودة جاهزاً للذكاء الاصطناعي لصفحات الخدمات والمدونات والأسئلة الشائعة وصفحات الهبوط للترتيب في محركات البحث والخرائط والمنصات التوليدية.", es: "Creo contenido de alta calidad listo para IA para páginas de servicios, blogs, FAQs y landing pages para posicionar en motores de búsqueda, mapas y plataformas generativas.", pt: "Crio conteúdo de alta qualidade pronto para IA para páginas de serviços, blogs, FAQs e landing pages para ranquear em mecanismos de busca, mapas e plataformas generativas.", fr: "Je crée du contenu de haute qualité prêt pour l'IA pour les pages de services, blogs, FAQ et pages d'atterrissage pour se classer sur les moteurs de recherche, cartes et plateformes génératives.", it: "Creo contenuti di alta qualità pronti per l'IA per pagine di servizi, blog, FAQ e landing page per posizionarsi sui motori di ricerca, mappe e piattaforme generative.", de: "Ich erstelle hochwertige, KI-bereite Inhalte für Service-Seiten, Blogs, FAQs und Landing Pages für Rankings in Suchmaschinen, Karten und generativen Plattformen." },
  "services.linkBuilding": { en: "Link Building & Local Citations", ar: "بناء الروابط والاستشهادات المحلية", es: "Link Building y Citaciones Locales", pt: "Link Building e Citações Locais", fr: "Link Building et Citations Locales", it: "Link Building e Citazioni Locali", de: "Linkaufbau & Lokale Zitierungen" },
  "services.linkBuildingDesc": { en: "I build high-authority links and local citations to boost trust signals and improve visibility across search engines, maps, and AI-driven platforms.", ar: "أبني روابط عالية السلطة واستشهادات محلية لتعزيز إشارات الثقة وتحسين الظهور عبر محركات البحث والخرائط والمنصات المدفوعة بالذكاء الاصطناعي.", es: "Construyo enlaces de alta autoridad y citaciones locales para impulsar señales de confianza y mejorar la visibilidad en motores de búsqueda, mapas y plataformas impulsadas por IA.", pt: "Construo links de alta autoridade e citações locais para aumentar sinais de confiança e melhorar a visibilidade em mecanismos de busca, mapas e plataformas impulsionadas por IA.", fr: "Je construis des liens de haute autorité et des citations locales pour renforcer les signaux de confiance et améliorer la visibilité sur les moteurs de recherche, cartes et plateformes alimentées par l'IA.", it: "Costruisco link ad alta autorità e citazioni locali per aumentare i segnali di fiducia e migliorare la visibilità sui motori di ricerca, mappe e piattaforme alimentate dall'IA.", de: "Ich baue hochwertige Links und lokale Zitierungen auf, um Vertrauenssignale zu stärken und die Sichtbarkeit in Suchmaschinen, Karten und KI-gesteuerten Plattformen zu verbessern." },
  "services.analytics": { en: "Conversion Tracking & Analytics", ar: "تتبع التحويلات والتحليلات", es: "Seguimiento de Conversiones y Analytics", pt: "Rastreamento de Conversões e Analytics", fr: "Suivi des conversions et Analytics", it: "Tracciamento conversioni e Analytics", de: "Conversion-Tracking & Analytics" },
  "services.analyticsDesc": { en: "I set up GA4, GTM, UTM tracking, and advanced analytics to track traffic, calls, map clicks, and conversions with actionable insights.", ar: "أقوم بإعداد GA4 وGTM وتتبع UTM والتحليلات المتقدمة لتتبع حركة المرور والمكالمات ونقرات الخرائط والتحويلات مع رؤى قابلة للتنفيذ.", es: "Configuro GA4, GTM, seguimiento UTM y analytics avanzados para rastrear tráfico, llamadas, clics en mapas y conversiones con insights accionables.", pt: "Configuro GA4, GTM, rastreamento UTM e analytics avançados para rastrear tráfego, chamadas, cliques em mapas e conversões com insights acionáveis.", fr: "Je configure GA4, GTM, le suivi UTM et des analyses avancées pour suivre le trafic, les appels, les clics sur les cartes et les conversions avec des insights exploitables.", it: "Configuro GA4, GTM, tracciamento UTM e analytics avanzati per tracciare traffico, chiamate, clic sulle mappe e conversioni con insights azionabili.", de: "Ich richte GA4, GTM, UTM-Tracking und erweiterte Analytics ein, um Traffic, Anrufe, Kartenklicks und Conversions mit umsetzbaren Erkenntnissen zu verfolgen." },
  "services.projectMgmt": { en: "Full-Stack Project Management", ar: "إدارة المشاريع الشاملة", es: "Gestión de Proyectos Full-Stack", pt: "Gerenciamento de Projetos Full-Stack", fr: "Gestion de projet Full-Stack", it: "Gestione progetti Full-Stack", de: "Full-Stack Projektmanagement" },
  "services.projectMgmtDesc": { en: "I manage all SEO, AI, and map optimization projects end-to-end, ensuring timely execution, performance tracking, and alignment with business goals.", ar: "أدير جميع مشاريع SEO والذكاء الاصطناعي وتحسين الخرائط من البداية للنهاية، مع ضمان التنفيذ في الوقت المناسب وتتبع الأداء والتوافق مع أهداف العمل.", es: "Gestiono todos los proyectos de SEO, IA y optimización de mapas de principio a fin, asegurando ejecución oportuna, seguimiento de rendimiento y alineación con objetivos comerciales.", pt: "Gerencio todos os projetos de SEO, IA e otimização de mapas de ponta a ponta, garantindo execução oportuna, rastreamento de desempenho e alinhamento com objetivos de negócios.", fr: "Je gère tous les projets SEO, IA et optimisation de cartes de bout en bout, assurant une exécution rapide, un suivi des performances et un alignement avec les objectifs commerciaux.", it: "Gestisco tutti i progetti SEO, IA e ottimizzazione mappe end-to-end, garantendo esecuzione tempestiva, tracciamento delle prestazioni e allineamento con gli obiettivi aziendali.", de: "Ich manage alle SEO-, KI- und Kartenoptimierungsprojekte End-to-End mit zeitnaher Ausführung, Performance-Tracking und Ausrichtung an Geschäftszielen." },
  "services.clientComm": { en: "Client Communication & Reporting", ar: "التواصل مع العملاء والتقارير", es: "Comunicación con Clientes y Reportes", pt: "Comunicação com Clientes e Relatórios", fr: "Communication client et rapports", it: "Comunicazione clienti e reportistica", de: "Kundenkommunikation & Reporting" },
  "services.clientCommDesc": { en: "I provide transparent, regular updates with insights on search performance, map visibility, AI ranking signals, and lead generation.", ar: "أقدم تحديثات شفافة ومنتظمة مع رؤى حول أداء البحث وظهور الخرائط وإشارات ترتيب الذكاء الاصطناعي وتوليد العملاء المحتملين.", es: "Proporciono actualizaciones transparentes y regulares con insights sobre rendimiento de búsqueda, visibilidad en mapas, señales de ranking IA y generación de leads.", pt: "Forneço atualizações transparentes e regulares com insights sobre desempenho de busca, visibilidade em mapas, sinais de ranking de IA e geração de leads.", fr: "Je fournis des mises à jour transparentes et régulières avec des insights sur les performances de recherche, la visibilité des cartes, les signaux de classement IA et la génération de leads.", it: "Fornisco aggiornamenti trasparenti e regolari con insights sulle prestazioni di ricerca, visibilità delle mappe, segnali di ranking IA e generazione di lead.", de: "Ich liefere transparente, regelmäßige Updates mit Einblicken in Suchperformance, Kartensichtbarkeit, KI-Ranking-Signale und Lead-Generierung." },
  "services.aiSeo": { en: "Advanced AI & Generative SEO", ar: "SEO المتقدم والتوليدي بالذكاء الاصطناعي", es: "SEO Avanzado de IA y Generativo", pt: "SEO Avançado de IA e Generativo", fr: "SEO avancé IA et génératif", it: "SEO avanzato IA e generativo", de: "Fortgeschrittenes KI & Generatives SEO" },
  "services.aiSeoDesc": { en: "I implement strategies to get your business cited by ChatGPT, Perplexity, Bing AI, You.com, and other generative engines for future-ready SEO.", ar: "أنفذ استراتيجيات لجعل عملك مذكوراً من قبل ChatGPT وPerplexity وBing AI وYou.com ومحركات توليدية أخرى لـ SEO جاهز للمستقبل.", es: "Implemento estrategias para que tu negocio sea citado por ChatGPT, Perplexity, Bing AI, You.com y otros motores generativos para SEO preparado para el futuro.", pt: "Implemento estratégias para que seu negócio seja citado pelo ChatGPT, Perplexity, Bing AI, You.com e outros mecanismos generativos para SEO pronto para o futuro.", fr: "J'implémente des stratégies pour que votre entreprise soit citée par ChatGPT, Perplexity, Bing AI, You.com et d'autres moteurs génératifs pour un SEO prêt pour l'avenir.", it: "Implemento strategie per far citare la tua attività da ChatGPT, Perplexity, Bing AI, You.com e altri motori generativi per un SEO pronto per il futuro.", de: "Ich implementiere Strategien, damit Ihr Unternehmen von ChatGPT, Perplexity, Bing AI, You.com und anderen generativen Engines zitiert wird für zukunftssicheres SEO." },

  // About
  "about.title": { en: "About Me", ar: "عني", es: "Sobre Mí", pt: "Sobre Mim", fr: "À propos de moi", it: "Chi sono", de: "Über mich" },
  "about.subtitle": { en: "Your Partner in Local Search Success", ar: "شريكك في نجاح البحث المحلي", es: "Tu Socio en el Éxito de la Búsqueda Local", pt: "Seu Parceiro no Sucesso de Busca Local", fr: "Votre partenaire pour le succès de la recherche locale", it: "Il tuo partner per il successo nella ricerca locale", de: "Ihr Partner für lokalen Sucherfolg" },
  "about.description": { en: "I'm Syed Hadi Hussain, a full-stack local SEO specialist who helps local and service-based businesses get more visibility on Google and turn searches into real leads.", ar: "أنا سيد هادي حسين، متخصص SEO محلي شامل أساعد الشركات المحلية والخدمية على الحصول على مزيد من الظهور على Google وتحويل عمليات البحث إلى عملاء حقيقيين.", es: "Soy Syed Hadi Hussain, un especialista en SEO local completo que ayuda a empresas locales a obtener más visibilidad en Google y convertir búsquedas en clientes reales.", pt: "Sou Syed Hadi Hussain, um especialista em SEO local completo que ajuda empresas locais a obter mais visibilidade no Google e converter pesquisas em leads reais.", fr: "Je suis Syed Hadi Hussain, un spécialiste SEO local complet qui aide les entreprises locales à obtenir plus de visibilité sur Google et à convertir les recherches en leads réels.", it: "Sono Syed Hadi Hussain, uno specialista SEO locale completo che aiuta le aziende locali a ottenere più visibilità su Google e a convertire le ricerche in lead reali.", de: "Ich bin Syed Hadi Hussain, ein Full-Stack Local SEO Spezialist, der lokalen Unternehmen hilft, mehr Sichtbarkeit bei Google zu erlangen und Suchen in echte Leads umzuwandeln." },
  "about.heading": { en: "Full-Stack Local SEO Specialist", ar: "متخصص SEO محلي شامل", es: "Especialista en SEO Local Full-Stack", pt: "Especialista em SEO Local Full-Stack", fr: "Spécialiste SEO local Full-Stack", it: "Specialista SEO locale Full-Stack", de: "Full-Stack Local SEO Spezialist" },
  "about.para1": { en: "I'm Syed Hadi Hussain, a full-stack local SEO specialist who helps local and service-based businesses get more visibility on Google and turn searches into real leads.", ar: "أنا سيد هادي حسين، متخصص SEO محلي شامل أساعد الشركات المحلية والخدمية على الحصول على مزيد من الظهور على Google وتحويل عمليات البحث إلى عملاء حقيقيين.", es: "Soy Syed Hadi Hussain, un especialista en SEO local completo que ayuda a empresas locales a obtener más visibilidad en Google y convertir búsquedas en clientes reales.", pt: "Sou Syed Hadi Hussain, um especialista em SEO local completo que ajuda empresas locais a obter mais visibilidade no Google e converter pesquisas em leads reais.", fr: "Je suis Syed Hadi Hussain, un spécialiste SEO local complet qui aide les entreprises locales à obtenir plus de visibilité sur Google et à convertir les recherches en leads réels.", it: "Sono Syed Hadi Hussain, uno specialista SEO locale completo che aiuta le aziende locali a ottenere più visibilità su Google e a convertire le ricerche in lead reali.", de: "Ich bin Syed Hadi Hussain, ein Full-Stack Local SEO Spezialist, der lokalen Unternehmen hilft, mehr Sichtbarkeit bei Google zu erlangen und Suchen in echte Leads umzuwandeln." },
  "about.para2": { en: "I don't just focus on rankings. I focus on what actually matters to your business, calls, inquiries, and customers. I manage the complete SEO process from strategy to execution, so you don't have to deal with multiple people or confusion.", ar: "لا أركز فقط على التصنيفات. أركز على ما يهم عملك حقاً: المكالمات والاستفسارات والعملاء. أدير عملية SEO الكاملة من الاستراتيجية إلى التنفيذ، لذلك لا تحتاج للتعامل مع أشخاص متعددين أو الارتباك.", es: "No solo me enfoco en los rankings. Me enfoco en lo que realmente importa para tu negocio: llamadas, consultas y clientes. Gestiono el proceso SEO completo desde la estrategia hasta la ejecución, para que no tengas que tratar con múltiples personas o confusión.", pt: "Não me concentro apenas em rankings. Concentro-me no que realmente importa para seu negócio: chamadas, consultas e clientes. Gerencio o processo completo de SEO da estratégia à execução, para que você não precise lidar com múltiplas pessoas ou confusão.", fr: "Je ne me concentre pas seulement sur les classements. Je me concentre sur ce qui compte vraiment pour votre entreprise : les appels, les demandes et les clients. Je gère le processus SEO complet de la stratégie à l'exécution, pour que vous n'ayez pas à gérer plusieurs personnes ou la confusion.", it: "Non mi concentro solo sui ranking. Mi concentro su ciò che conta davvero per la tua attività: chiamate, richieste e clienti. Gestisco l'intero processo SEO dalla strategia all'esecuzione, così non devi avere a che fare con più persone o confusione.", de: "Ich konzentriere mich nicht nur auf Rankings. Ich konzentriere mich auf das, was für Ihr Unternehmen wirklich zählt: Anrufe, Anfragen und Kunden. Ich manage den kompletten SEO-Prozess von der Strategie bis zur Umsetzung, damit Sie nicht mit mehreren Personen oder Verwirrung umgehen müssen." },
  "about.para3": { en: "With 7+ years of experience and 100+ clients served, I help businesses grow through clear, proven, and result-focused local SEO.", ar: "مع أكثر من 7 سنوات من الخبرة وخدمة أكثر من 100 عميل، أساعد الشركات على النمو من خلال SEO محلي واضح ومثبت ومركز على النتائج.", es: "Con más de 7 años de experiencia y más de 100 clientes atendidos, ayudo a las empresas a crecer a través de SEO local claro, probado y enfocado en resultados.", pt: "Com mais de 7 anos de experiência e mais de 100 clientes atendidos, ajudo empresas a crescer através de SEO local claro, comprovado e focado em resultados.", fr: "Avec plus de 7 ans d'expérience et plus de 100 clients servis, j'aide les entreprises à se développer grâce à un SEO local clair, éprouvé et axé sur les résultats.", it: "Con oltre 7 anni di esperienza e oltre 100 clienti serviti, aiuto le aziende a crescere attraverso un SEO locale chiaro, comprovato e focalizzato sui risultati.", de: "Mit über 7 Jahren Erfahrung und über 100 betreuten Kunden helfe ich Unternehmen durch klares, bewährtes und ergebnisorientiertes lokales SEO zu wachsen." },
  "about.yearsExp": { en: "Years Experience", ar: "سنوات الخبرة", es: "Años de Experiencia", pt: "Anos de Experiência", fr: "Années d'expérience", it: "Anni di esperienza", de: "Jahre Erfahrung" },
  "about.clientsServed": { en: "Clients Served", ar: "عملاء تم خدمتهم", es: "Clientes Atendidos", pt: "Clientes Atendidos", fr: "Clients servis", it: "Clienti serviti", de: "Betreute Kunden" },
  "about.getInTouch": { en: "Get in Touch", ar: "تواصل معنا", es: "Contáctanos", pt: "Entre em Contato", fr: "Contactez-nous", it: "Contattaci", de: "Kontaktieren Sie uns" },
  "about.connectWithMe": { en: "Connect with Me", ar: "تواصل معي", es: "Conéctate Conmigo", pt: "Conecte-se Comigo", fr: "Connectez-vous avec moi", it: "Connettiti con me", de: "Verbinden Sie sich mit mir" },
  "about.certifications": { en: "Certifications", ar: "الشهادات", es: "Certificaciones", pt: "Certificações", fr: "Certifications", it: "Certificazioni", de: "Zertifizierungen" },
  "about.keySkills": { en: "Key Skills & Expertise", ar: "المهارات والخبرات الرئيسية", es: "Habilidades y Experiencia Clave", pt: "Habilidades e Expertise Principais", fr: "Compétences et expertise clés", it: "Competenze e competenze chiave", de: "Kernkompetenzen & Expertise" },
  "about.scheduleMeeting": { en: "Schedule a Meeting", ar: "جدولة اجتماع", es: "Programar una Reunión", pt: "Agendar Reunião", fr: "Planifier une réunion", it: "Pianifica un incontro", de: "Meeting planen" },
  "about.bookOnCalendly": { en: "Book on Calendly", ar: "احجز على Calendly", es: "Reservar en Calendly", pt: "Agendar no Calendly", fr: "Réserver sur Calendly", it: "Prenota su Calendly", de: "Auf Calendly buchen" },

  // Testimonials
  "testimonials.title": { en: "What Clients Say", ar: "ماذا يقول العملاء", es: "Lo que Dicen los Clientes", pt: "O que os Clientes Dizem", fr: "Ce que disent les clients", it: "Cosa dicono i clienti", de: "Was Kunden sagen" },
  "testimonials.subtitle": { en: "Real results from real businesses", ar: "نتائج حقيقية من شركات حقيقية", es: "Resultados reales de negocios reales", pt: "Resultados reais de negócios reais", fr: "Résultats réels d'entreprises réelles", it: "Risultati reali da aziende reali", de: "Echte Ergebnisse von echten Unternehmen" },

  // FAQ
  "faq.title": { en: "Frequently Asked Questions", ar: "الأسئلة الشائعة", es: "Preguntas Frecuentes", pt: "Perguntas Frequentes", fr: "Questions fréquemment posées", it: "Domande frequenti", de: "Häufig gestellte Fragen" },
  "faq.subtitle": { en: "Everything you need to know about Local SEO", ar: "كل ما تحتاج معرفته عن SEO المحلي", es: "Todo lo que necesitas saber sobre SEO Local", pt: "Tudo o que você precisa saber sobre SEO Local", fr: "Tout ce que vous devez savoir sur le SEO local", it: "Tutto quello che devi sapere sul SEO locale", de: "Alles, was Sie über Local SEO wissen müssen" },
  "faq.description": { en: "Get answers to common questions about my SEO services and how I can help your business grow.", ar: "احصل على إجابات للأسئلة الشائعة حول خدمات SEO الخاصة بي وكيف يمكنني مساعدة عملك على النمو.", es: "Obtén respuestas a preguntas comunes sobre mis servicios SEO y cómo puedo ayudar a tu negocio a crecer.", pt: "Obtenha respostas para perguntas comuns sobre meus serviços de SEO e como posso ajudar seu negócio a crescer.", fr: "Obtenez des réponses aux questions courantes sur mes services SEO et comment je peux aider votre entreprise à se développer.", it: "Ottieni risposte alle domande comuni sui miei servizi SEO e su come posso aiutare la tua attività a crescere.", de: "Erhalten Sie Antworten auf häufige Fragen zu meinen SEO-Diensten und wie ich Ihrem Unternehmen beim Wachstum helfen kann." },

  // FAQ Questions
  "faq.q1": { en: "What exactly is Local SEO and Map SEO?", ar: "ما هو بالضبط SEO المحلي وSEO الخرائط؟", es: "¿Qué es exactamente SEO Local y SEO de Mapas?", pt: "O que exatamente é SEO Local e SEO de Mapas?", fr: "Qu'est-ce que le SEO local et le SEO Maps exactement?", it: "Cos'è esattamente il SEO locale e il SEO Mappe?", de: "Was genau ist Local SEO und Maps SEO?" },
  "faq.a1": { en: "Local SEO and Map SEO help your business appear on Google Maps, Apple Maps, Bing Maps, and local searches, making it easy for nearby customers to find you and contact you.", ar: "يساعد SEO المحلي وSEO الخرائط عملك على الظهور على خرائط Google وApple وBing والبحث المحلي، مما يسهل على العملاء القريبين العثور عليك والاتصال بك.", es: "El SEO Local y SEO de Mapas ayudan a tu negocio a aparecer en Google Maps, Apple Maps, Bing Maps y búsquedas locales, facilitando que los clientes cercanos te encuentren y contacten.", pt: "SEO Local e SEO de Mapas ajudam seu negócio a aparecer no Google Maps, Apple Maps, Bing Maps e pesquisas locais, facilitando que clientes próximos encontrem e entrem em contato com você.", fr: "Le SEO local et le SEO Maps aident votre entreprise à apparaître sur Google Maps, Apple Maps, Bing Maps et les recherches locales, facilitant la recherche et le contact par les clients proches.", it: "Il SEO locale e il SEO Mappe aiutano la tua attività ad apparire su Google Maps, Apple Maps, Bing Maps e ricerche locali, facilitando ai clienti vicini di trovarti e contattarti.", de: "Local SEO und Maps SEO helfen Ihrem Unternehmen, auf Google Maps, Apple Maps, Bing Maps und in lokalen Suchen zu erscheinen, damit Kunden in der Nähe Sie leicht finden und kontaktieren können." },
  "faq.q2": { en: "What is Google Business Profile Management?", ar: "ما هي إدارة ملف Google التجاري؟", es: "¿Qué es la Gestión de Google Business Profile?", pt: "O que é Gerenciamento de Google Business Profile?", fr: "Qu'est-ce que la gestion de Google Business Profile?", it: "Cos'è la gestione di Google Business Profile?", de: "Was ist Google Business Profile Management?" },
  "faq.a2": { en: "I optimize your Google Business Profile to ensure your business ranks higher in search, maps, and AI-powered platforms, showing accurate info to potential customers.", ar: "أقوم بتحسين ملف Google التجاري الخاص بك لضمان ترتيب أعلى لعملك في البحث والخرائط والمنصات المدعومة بالذكاء الاصطناعي، مع عرض معلومات دقيقة للعملاء المحتملين.", es: "Optimizo tu Google Business Profile para asegurar que tu negocio tenga un ranking más alto en búsqueda, mapas y plataformas con IA, mostrando información precisa a clientes potenciales.", pt: "Otimizo seu Google Business Profile para garantir que seu negócio tenha um ranking mais alto em pesquisa, mapas e plataformas com IA, mostrando informações precisas para clientes potenciais.", fr: "J'optimise votre Google Business Profile pour assurer que votre entreprise soit mieux classée dans la recherche, les cartes et les plateformes alimentées par l'IA, affichant des informations précises aux clients potentiels.", it: "Ottimizzo il tuo Google Business Profile per assicurare che la tua attività si posizioni più in alto nella ricerca, mappe e piattaforme alimentate dall'IA, mostrando informazioni accurate ai potenziali clienti.", de: "Ich optimiere Ihr Google Business Profile, damit Ihr Unternehmen in Suche, Karten und KI-gestützten Plattformen höher rankt und potenziellen Kunden genaue Informationen zeigt." },
  "faq.q3": { en: "How does Keyword Research & Semantic SEO help my business?", ar: "كيف يساعد بحث الكلمات المفتاحية وSEO الدلالي عملي؟", es: "¿Cómo ayuda la Investigación de Palabras Clave y SEO Semántico a mi negocio?", pt: "Como a Pesquisa de Palavras-chave e SEO Semântico ajudam meu negócio?", fr: "Comment la recherche de mots-clés et le SEO sémantique aident-ils mon entreprise?", it: "Come la ricerca di parole chiave e il SEO semantico aiutano la mia attività?", de: "Wie hilft Keyword-Recherche und semantisches SEO meinem Unternehmen?" },
  "faq.a3": { en: "I find the right keywords your customers are searching for—including voice, AI, and generative search queries—so your business gets visible traffic that converts into leads.", ar: "أجد الكلمات المفتاحية الصحيحة التي يبحث عنها عملاؤك—بما في ذلك البحث الصوتي والذكاء الاصطناعي واستعلامات البحث التوليدية—ليحصل عملك على حركة مرور مرئية تتحول إلى عملاء محتملين.", es: "Encuentro las palabras clave correctas que tus clientes buscan—incluyendo voz, IA y consultas de búsqueda generativa—para que tu negocio obtenga tráfico visible que se convierte en leads.", pt: "Encontro as palavras-chave certas que seus clientes estão pesquisando—incluindo voz, IA e consultas de pesquisa generativa—para que seu negócio obtenha tráfego visível que se converte em leads.", fr: "Je trouve les bons mots-clés que vos clients recherchent—y compris les recherches vocales, IA et génératives—pour que votre entreprise obtienne un trafic visible qui se convertit en leads.", it: "Trovo le parole chiave giuste che i tuoi clienti stanno cercando—incluse ricerche vocali, IA e query di ricerca generative—affinché la tua attività ottenga traffico visibile che si converte in lead.", de: "Ich finde die richtigen Keywords, nach denen Ihre Kunden suchen—einschließlich Sprach-, KI- und generative Suchanfragen—damit Ihr Unternehmen sichtbaren Traffic erhält, der in Leads umgewandelt wird." },
  "faq.q4": { en: "What is AI-Optimized Content & Generative SEO?", ar: "ما هو المحتوى المحسن للذكاء الاصطناعي وSEO التوليدي؟", es: "¿Qué es el Contenido Optimizado para IA y SEO Generativo?", pt: "O que é Conteúdo Otimizado para IA e SEO Generativo?", fr: "Qu'est-ce que le contenu optimisé pour l'IA et le SEO génératif?", it: "Cos'è il contenuto ottimizzato per l'IA e il SEO generativo?", de: "Was ist KI-optimierter Inhalt und generatives SEO?" },
  "faq.a4": { en: "I create content optimized for search engines, AI assistants, and generative platforms like ChatGPT and Perplexity, helping your business stay ahead of future search trends.", ar: "أنشئ محتوى محسناً لمحركات البحث ومساعدي الذكاء الاصطناعي والمنصات التوليدية مثل ChatGPT وPerplexity، مما يساعد عملك على البقاء في صدارة اتجاهات البحث المستقبلية.", es: "Creo contenido optimizado para motores de búsqueda, asistentes de IA y plataformas generativas como ChatGPT y Perplexity, ayudando a tu negocio a mantenerse adelante de las tendencias de búsqueda futuras.", pt: "Crio conteúdo otimizado para mecanismos de busca, assistentes de IA e plataformas generativas como ChatGPT e Perplexity, ajudando seu negócio a ficar à frente das tendências de busca futuras.", fr: "Je crée du contenu optimisé pour les moteurs de recherche, les assistants IA et les plateformes génératives comme ChatGPT et Perplexity, aidant votre entreprise à rester en avance sur les tendances de recherche futures.", it: "Creo contenuti ottimizzati per motori di ricerca, assistenti IA e piattaforme generative come ChatGPT e Perplexity, aiutando la tua attività a restare avanti rispetto alle tendenze di ricerca future.", de: "Ich erstelle Inhalte, die für Suchmaschinen, KI-Assistenten und generative Plattformen wie ChatGPT und Perplexity optimiert sind, damit Ihr Unternehmen zukünftigen Suchtrends voraus bleibt." },
  "faq.q5": { en: "Can you manage my entire digital marketing?", ar: "هل يمكنك إدارة التسويق الرقمي بالكامل؟", es: "¿Puedes gestionar todo mi marketing digital?", pt: "Você pode gerenciar todo meu marketing digital?", fr: "Pouvez-vous gérer tout mon marketing numérique?", it: "Puoi gestire tutto il mio marketing digitale?", de: "Können Sie mein gesamtes digitales Marketing verwalten?" },
  "faq.a5": { en: "Yes! I handle website design, campaigns, social media, ads, AI assistants, chatbots, and project management so you can focus on running your business while I grow it online.", ar: "نعم! أتولى تصميم المواقع والحملات ووسائل التواصل الاجتماعي والإعلانات ومساعدي الذكاء الاصطناعي والروبوتات وإدارة المشاريع حتى تتمكن من التركيز على إدارة عملك بينما أنميه عبر الإنترنت.", es: "¡Sí! Manejo diseño web, campañas, redes sociales, anuncios, asistentes de IA, chatbots y gestión de proyectos para que puedas enfocarte en tu negocio mientras yo lo hago crecer en línea.", pt: "Sim! Cuido de design de sites, campanhas, mídias sociais, anúncios, assistentes de IA, chatbots e gerenciamento de projetos para que você possa se concentrar em administrar seu negócio enquanto eu o faço crescer online.", fr: "Oui! Je gère la conception de sites web, les campagnes, les médias sociaux, les publicités, les assistants IA, les chatbots et la gestion de projet pour que vous puissiez vous concentrer sur votre entreprise pendant que je la fais croître en ligne.", it: "Sì! Gestisco design di siti web, campagne, social media, annunci, assistenti IA, chatbot e gestione progetti così puoi concentrarti sulla tua attività mentre io la faccio crescere online.", de: "Ja! Ich übernehme Website-Design, Kampagnen, Social Media, Anzeigen, KI-Assistenten, Chatbots und Projektmanagement, damit Sie sich auf Ihr Geschäft konzentrieren können, während ich es online wachsen lasse." },
  "faq.q6": { en: "How do I start?", ar: "كيف أبدأ؟", es: "¿Cómo empiezo?", pt: "Como começo?", fr: "Comment puis-je commencer?", it: "Come inizio?", de: "Wie fange ich an?" },
  "faq.a6": { en: "Just share your business goals, and we'll schedule a strategy call to create a custom plan for your growth. Every step is transparent, measurable, and designed to increase leads and revenue.", ar: "فقط شارك أهداف عملك، وسنحدد موعداً لمكالمة استراتيجية لإنشاء خطة مخصصة لنموك. كل خطوة شفافة وقابلة للقياس ومصممة لزيادة العملاء المحتملين والإيرادات.", es: "Solo comparte tus objetivos comerciales, y programaremos una llamada estratégica para crear un plan personalizado para tu crecimiento. Cada paso es transparente, medible y diseñado para aumentar leads e ingresos.", pt: "Apenas compartilhe seus objetivos de negócios, e agendaremos uma chamada estratégica para criar um plano personalizado para seu crescimento. Cada passo é transparente, mensurável e projetado para aumentar leads e receita.", fr: "Partagez simplement vos objectifs commerciaux, et nous programmerons un appel stratégique pour créer un plan personnalisé pour votre croissance. Chaque étape est transparente, mesurable et conçue pour augmenter les leads et les revenus.", it: "Basta condividere i tuoi obiettivi aziendali, e programmeremo una chiamata strategica per creare un piano personalizzato per la tua crescita. Ogni passo è trasparente, misurabile e progettato per aumentare lead e ricavi.", de: "Teilen Sie einfach Ihre Geschäftsziele mit, und wir vereinbaren einen Strategieanruf, um einen maßgeschneiderten Plan für Ihr Wachstum zu erstellen. Jeder Schritt ist transparent, messbar und darauf ausgelegt, Leads und Umsatz zu steigern." },

  // Footer
  "footer.rights": { en: "All rights reserved.", ar: "جميع الحقوق محفوظة.", es: "Todos los derechos reservados.", pt: "Todos os direitos reservados.", fr: "Tous droits réservés.", it: "Tutti i diritti riservati.", de: "Alle Rechte vorbehalten." },
  "footer.privacy": { en: "Privacy Policy", ar: "سياسة الخصوصية", es: "Política de Privacidad", pt: "Política de Privacidade", fr: "Politique de confidentialité", it: "Informativa sulla privacy", de: "Datenschutzrichtlinie" },
  "footer.terms": { en: "Terms of Service", ar: "شروط الخدمة", es: "Términos de Servicio", pt: "Termos de Serviço", fr: "Conditions d'utilisation", it: "Termini di servizio", de: "Nutzungsbedingungen" },
  "footer.tagline": { en: "Trusted by 100+ businesses worldwide for proven SEO results.", ar: "موثوق به من قبل أكثر من 100 شركة حول العالم لنتائج SEO مثبتة.", es: "Confiado por más de 100 empresas en todo el mundo para resultados SEO comprobados.", pt: "Confiado por mais de 100 empresas em todo o mundo para resultados SEO comprovados.", fr: "Approuvé par plus de 100 entreprises dans le monde pour des résultats SEO prouvés.", it: "Affidabile da oltre 100 aziende in tutto il mondo per risultati SEO comprovati.", de: "Von über 100 Unternehmen weltweit für bewiesene SEO-Ergebnisse vertraut." },
  "footer.payments": { en: "Accepted Payments", ar: "طرق الدفع المقبولة", es: "Pagos Aceptados", pt: "Pagamentos Aceitos", fr: "Paiements acceptés", it: "Pagamenti accettati", de: "Akzeptierte Zahlungen" },
  "footer.description": { en: "Helping local businesses dominate Google Search and Maps with proven SEO strategies that deliver real results.", ar: "مساعدة الشركات المحلية على السيطرة على بحث Google والخرائط باستراتيجيات SEO مثبتة تحقق نتائج حقيقية.", es: "Ayudando a negocios locales a dominar Google Search y Maps con estrategias SEO probadas que entregan resultados reales.", pt: "Ajudando empresas locais a dominar o Google Search e Maps com estratégias de SEO comprovadas que entregam resultados reais.", fr: "Aider les entreprises locales à dominer Google Search et Maps avec des stratégies SEO éprouvées qui livrent de vrais résultats.", it: "Aiutando le aziende locali a dominare Google Search e Maps con strategie SEO comprovate che forniscono risultati reali.", de: "Ich helfe lokalen Unternehmen, Google Search und Maps mit bewährten SEO-Strategien zu dominieren, die echte Ergebnisse liefern." },
  "footer.trustBadge": { en: "100+ Clients Worldwide", ar: "أكثر من 100 عميل حول العالم", es: "100+ Clientes en Todo el Mundo", pt: "100+ Clientes no Mundo Todo", fr: "100+ Clients dans le monde", it: "100+ Clienti nel mondo", de: "100+ Kunden weltweit" },
  "footer.servingWorldwide": { en: "Serving Clients Worldwide", ar: "خدمة العملاء حول العالم", es: "Atendiendo Clientes en Todo el Mundo", pt: "Atendendo Clientes no Mundo Todo", fr: "Au service des clients du monde entier", it: "Al servizio di clienti in tutto il mondo", de: "Kunden weltweit bedienen" },
  "footer.followTips": { en: "Follow me for tips and updates on local SEO strategies.", ar: "تابعني للحصول على نصائح وتحديثات حول استراتيجيات SEO المحلية.", es: "Sígueme para consejos y actualizaciones sobre estrategias de SEO local.", pt: "Siga-me para dicas e atualizações sobre estratégias de SEO local.", fr: "Suivez-moi pour des conseils et mises à jour sur les stratégies SEO locales.", it: "Seguimi per consigli e aggiornamenti sulle strategie SEO locali.", de: "Folgen Sie mir für Tipps und Updates zu lokalen SEO-Strategien." },
  "footer.connect": { en: "Connect", ar: "تواصل", es: "Conectar", pt: "Conectar", fr: "Se connecter", it: "Connetti", de: "Verbinden" },

  // Portfolio
  "portfolio.title": { en: "Our Portfolio", ar: "محفظتنا", es: "Nuestro Portafolio", pt: "Nosso Portfólio", fr: "Notre Portfolio", it: "Il nostro Portfolio", de: "Unser Portfolio" },
  "portfolio.webDev": { en: "Web Development", ar: "تطوير المواقع", es: "Desarrollo Web", pt: "Desenvolvimento Web", fr: "Développement Web", it: "Sviluppo Web", de: "Webentwicklung" },
  "portfolio.seo": { en: "SEO Results", ar: "نتائج SEO", es: "Resultados SEO", pt: "Resultados SEO", fr: "Résultats SEO", it: "Risultati SEO", de: "SEO-Ergebnisse" },

  // CTA
  "cta.beyondSeo": { en: "Beyond SEO", ar: "ما وراء SEO", es: "Más Allá del SEO", pt: "Além do SEO", fr: "Au-delà du SEO", it: "Oltre il SEO", de: "Über SEO hinaus" },
  "cta.title": { en: "Grow Your Business Online – From SEO to Full Digital Solutions", ar: "نمِّ عملك عبر الإنترنت - من SEO إلى حلول رقمية كاملة", es: "Haga Crecer Su Negocio en Línea – Desde SEO hasta Soluciones Digitales Completas", pt: "Cresça Seu Negócio Online – De SEO a Soluções Digitais Completas", fr: "Développez votre entreprise en ligne – Du SEO aux solutions numériques complètes", it: "Fai crescere la tua attività online – Dal SEO alle soluzioni digitali complete", de: "Wachsen Sie online – Von SEO bis zu kompletten digitalen Lösungen" },
  "cta.description": { en: "As a Local SEO specialist, I help businesses get more visibility, leads, and sales online. Beyond that, you can also hire me as your full-stack project manager to manage everything, so your business grows smoothly without juggling multiple vendors.", ar: "بصفتي متخصصًا في SEO المحلي، أساعد الشركات على الحصول على مزيد من الظهور والعملاء والمبيعات عبر الإنترنت. بالإضافة إلى ذلك، يمكنك توظيفي كمدير مشروع شامل لإدارة كل شيء.", es: "Como especialista en SEO local, ayudo a las empresas a obtener más visibilidad, clientes potenciales y ventas en línea. Además, también puedes contratarme como tu gerente de proyectos completo.", pt: "Como especialista em SEO local, ajudo empresas a obter mais visibilidade, leads e vendas online. Além disso, você também pode me contratar como seu gerente de projetos completo.", fr: "En tant que spécialiste du SEO local, j'aide les entreprises à obtenir plus de visibilité, de leads et de ventes en ligne. De plus, vous pouvez également m'engager comme votre chef de projet complet.", it: "Come specialista SEO locale, aiuto le aziende a ottenere più visibilità, lead e vendite online. Inoltre, puoi anche assumermi come tuo project manager completo.", de: "Als Local SEO Spezialist helfe ich Unternehmen, mehr Sichtbarkeit, Leads und Verkäufe online zu erzielen. Darüber hinaus können Sie mich auch als Ihren Full-Stack-Projektmanager engagieren." },
  "cta.bookStrategy": { en: "Book a Strategy Call", ar: "احجز مكالمة استراتيجية", es: "Reserve una Llamada Estratégica", pt: "Agende uma Chamada Estratégica", fr: "Réservez un appel stratégique", it: "Prenota una chiamata strategica", de: "Strategiegespräch buchen" },
  "cta.shareGoals": { en: "Share Your Goals", ar: "شارك أهدافك", es: "Comparte Tus Objetivos", pt: "Compartilhe Seus Objetivos", fr: "Partagez vos objectifs", it: "Condividi i tuoi obiettivi", de: "Teilen Sie Ihre Ziele" },
  "cta.viewProjects": { en: "View Successful Projects", ar: "عرض المشاريع الناجحة", es: "Ver Proyectos Exitosos", pt: "Ver Projetos de Sucesso", fr: "Voir les projets réussis", it: "Vedi progetti di successo", de: "Erfolgreiche Projekte ansehen" },
  "cta.goal": { en: "My goal is simple: deliver more leads, more sales, and better online visibility with a clear, custom strategy.", ar: "هدفي بسيط: تقديم المزيد من العملاء المحتملين والمبيعات ورؤية أفضل عبر الإنترنت مع استراتيجية واضحة ومخصصة.", es: "Mi objetivo es simple: entregar más leads, más ventas y mejor visibilidad en línea con una estrategia clara y personalizada.", pt: "Meu objetivo é simples: entregar mais leads, mais vendas e melhor visibilidade online com uma estratégia clara e personalizada.", fr: "Mon objectif est simple: fournir plus de leads, plus de ventes et une meilleure visibilité en ligne avec une stratégie claire et personnalisée.", it: "Il mio obiettivo è semplice: fornire più lead, più vendite e una migliore visibilità online con una strategia chiara e personalizzata.", de: "Mein Ziel ist einfach: mehr Leads, mehr Verkäufe und bessere Online-Sichtbarkeit mit einer klaren, maßgeschneiderten Strategie." },

  // Common
  "common.learnMore": { en: "Learn More", ar: "اعرف المزيد", es: "Más Información", pt: "Saiba Mais", fr: "En savoir plus", it: "Scopri di più", de: "Mehr erfahren" },
  "common.viewAll": { en: "View All", ar: "عرض الكل", es: "Ver Todo", pt: "Ver Tudo", fr: "Voir tout", it: "Vedi tutto", de: "Alle ansehen" },
  "common.readMore": { en: "Read More", ar: "اقرأ المزيد", es: "Leer Más", pt: "Leia Mais", fr: "Lire la suite", it: "Leggi di più", de: "Mehr lesen" },
  "common.getAudit": { en: "Get SEO Audit", ar: "احصل على تدقيق SEO", es: "Obtener Auditoría SEO", pt: "Obter Auditoria SEO", fr: "Obtenir un audit SEO", it: "Ottieni Audit SEO", de: "SEO-Audit erhalten" },

  // Pricing
  "pricing.title": { en: "Transparent Pricing for Every Business", ar: "أسعار شفافة لكل عمل", es: "Precios Transparentes para Cada Negocio", pt: "Preços Transparentes para Cada Negócio", fr: "Tarification transparente pour chaque entreprise", it: "Prezzi trasparenti per ogni azienda", de: "Transparente Preise für jedes Unternehmen" },
  "pricing.subtitle": { en: "Choose Your Plan", ar: "اختر خطتك", es: "Elige Tu Plan", pt: "Escolha Seu Plano", fr: "Choisissez votre plan", it: "Scegli il tuo piano", de: "Wählen Sie Ihren Plan" },
  "pricing.description": { en: "Affordable SEO solutions with proven results. No hidden fees, no long-term contracts.", ar: "حلول SEO بأسعار معقولة مع نتائج مثبتة. لا رسوم خفية، لا عقود طويلة الأجل.", es: "Soluciones SEO asequibles con resultados comprobados. Sin tarifas ocultas, sin contratos a largo plazo.", pt: "Soluções de SEO acessíveis com resultados comprovados. Sem taxas ocultas, sem contratos de longo prazo.", fr: "Solutions SEO abordables avec des résultats prouvés. Pas de frais cachés, pas de contrats à long terme.", it: "Soluzioni SEO accessibili con risultati comprovati. Nessun costo nascosto, nessun contratto a lungo termine.", de: "Erschwingliche SEO-Lösungen mit nachgewiesenen Ergebnissen. Keine versteckten Gebühren, keine langfristigen Verträge." },
  "pricing.limitedTime": { en: "Limited Time", ar: "وقت محدود", es: "Tiempo Limitado", pt: "Tempo Limitado", fr: "Temps limité", it: "Tempo limitato", de: "Begrenzte Zeit" },
  "pricing.offAll": { en: "25% OFF All Packages!", ar: "خصم 25% على جميع الباقات!", es: "¡25% DESCUENTO en Todos los Paquetes!", pt: "25% DESCONTO em Todos os Pacotes!", fr: "25% DE RÉDUCTION sur tous les forfaits!", it: "25% DI SCONTO su tutti i pacchetti!", de: "25% RABATT auf alle Pakete!" },
  "pricing.signUpIn3Days": { en: "Sign up within 3 days and save big on any service package", ar: "سجل خلال 3 أيام ووفر الكثير على أي باقة خدمات", es: "Regístrate en 3 días y ahorra mucho en cualquier paquete de servicios", pt: "Inscreva-se em 3 dias e economize muito em qualquer pacote de serviços", fr: "Inscrivez-vous dans les 3 jours et économisez gros sur n'importe quel forfait", it: "Iscriviti entro 3 giorni e risparmia molto su qualsiasi pacchetto di servizi", de: "Melden Sie sich innerhalb von 3 Tagen an und sparen Sie viel bei jedem Servicepaket" },
  "pricing.claimDiscount": { en: "Claim Your 25% Discount", ar: "احصل على خصم 25%", es: "Reclama Tu 25% de Descuento", pt: "Reivindique Seu 25% de Desconto", fr: "Réclamez votre réduction de 25%", it: "Richiedi il tuo sconto del 25%", de: "Fordern Sie Ihren 25% Rabatt an" },
  "pricing.mostPopular": { en: "Most Popular", ar: "الأكثر شعبية", es: "Más Popular", pt: "Mais Popular", fr: "Le plus populaire", it: "Più popolare", de: "Am beliebtesten" },
  "pricing.guarantees": { en: "Our Guarantees", ar: "ضماناتنا", es: "Nuestras Garantías", pt: "Nossas Garantias", fr: "Nos garanties", it: "Le nostre garanzie", de: "Unsere Garantien" },
  "pricing.resultsGuaranteed": { en: "Results Guaranteed", ar: "نتائج مضمونة", es: "Resultados Garantizados", pt: "Resultados Garantidos", fr: "Résultats garantis", it: "Risultati garantiti", de: "Ergebnisse garantiert" },
  "pricing.resultsGuaranteedDesc": { en: "If you don't see improvement in 90 days, we'll work for free until you do.", ar: "إذا لم تر تحسناً في 90 يوماً، سنعمل مجاناً حتى ترى التحسن.", es: "Si no ves mejoras en 90 días, trabajaremos gratis hasta que las veas.", pt: "Se você não ver melhoria em 90 dias, trabalharemos de graça até você ver.", fr: "Si vous ne voyez pas d'amélioration en 90 jours, nous travaillerons gratuitement jusqu'à ce que vous en voyiez.", it: "Se non vedi miglioramenti in 90 giorni, lavoreremo gratis finché non li vedrai.", de: "Wenn Sie in 90 Tagen keine Verbesserung sehen, arbeiten wir kostenlos, bis Sie es tun." },
  "pricing.quickTurnaround": { en: "Quick Turnaround", ar: "تسليم سريع", es: "Entrega Rápida", pt: "Entrega Rápida", fr: "Délai rapide", it: "Consegna rapida", de: "Schnelle Bearbeitung" },
  "pricing.quickTurnaroundDesc": { en: "Audit reports delivered within 48-72 hours. No long waits.", ar: "تسليم تقارير التدقيق خلال 48-72 ساعة. لا انتظار طويل.", es: "Informes de auditoría entregados en 48-72 horas. Sin largas esperas.", pt: "Relatórios de auditoria entregues em 48-72 horas. Sem longas esperas.", fr: "Rapports d'audit livrés en 48-72 heures. Pas de longues attentes.", it: "Report di audit consegnati in 48-72 ore. Nessuna lunga attesa.", de: "Audit-Berichte werden innerhalb von 48-72 Stunden geliefert. Keine langen Wartezeiten." },
  "pricing.provenTrack": { en: "Proven Track Record", ar: "سجل حافل مثبت", es: "Historial Probado", pt: "Histórico Comprovado", fr: "Bilan éprouvé", it: "Track record comprovato", de: "Nachgewiesene Erfolgsbilanz" },
  "pricing.provenTrackDesc": { en: "100+ businesses helped with an average 150% traffic increase.", ar: "مساعدة أكثر من 100 شركة بمتوسط زيادة في الزيارات 150%.", es: "100+ negocios ayudados con un aumento promedio del 150% en tráfico.", pt: "100+ empresas ajudadas com um aumento médio de 150% no tráfego.", fr: "100+ entreprises aidées avec une augmentation moyenne de 150% du trafic.", it: "100+ aziende aiutate con un aumento medio del traffico del 150%.", de: "100+ Unternehmen geholfen mit durchschnittlich 150% Traffic-Steigerung." },
  "pricing.haveQuestions": { en: "Have Questions?", ar: "لديك أسئلة؟", es: "¿Tienes Preguntas?", pt: "Tem Perguntas?", fr: "Vous avez des questions?", it: "Hai domande?", de: "Haben Sie Fragen?" },
  "pricing.checkFaq": { en: "Check our FAQ or get in touch for custom solutions tailored to your needs.", ar: "تحقق من الأسئلة الشائعة أو تواصل معنا للحصول على حلول مخصصة تناسب احتياجاتك.", es: "Consulta nuestras FAQ o contáctanos para soluciones personalizadas a tu medida.", pt: "Confira nosso FAQ ou entre em contato para soluções personalizadas às suas necessidades.", fr: "Consultez notre FAQ ou contactez-nous pour des solutions personnalisées adaptées à vos besoins.", it: "Controlla le nostre FAQ o contattaci per soluzioni personalizzate su misura per le tue esigenze.", de: "Schauen Sie sich unsere FAQ an oder kontaktieren Sie uns für maßgeschneiderte Lösungen." },
  "pricing.viewFaq": { en: "View FAQ", ar: "عرض الأسئلة الشائعة", es: "Ver FAQ", pt: "Ver FAQ", fr: "Voir FAQ", it: "Vedi FAQ", de: "FAQ ansehen" },
  "pricing.viewCaseStudies": { en: "View Case Studies", ar: "عرض دراسات الحالة", es: "Ver Casos de Estudio", pt: "Ver Estudos de Caso", fr: "Voir les études de cas", it: "Vedi casi di studio", de: "Fallstudien ansehen" },
  "pricing.contactUs": { en: "Contact Us", ar: "اتصل بنا", es: "Contáctanos", pt: "Contate-nos", fr: "Contactez-nous", it: "Contattaci", de: "Kontaktieren Sie uns" },

  // Discount countdown
  "discount.days": { en: "Days", ar: "أيام", es: "Días", pt: "Dias", fr: "Jours", it: "Giorni", de: "Tage" },
  "discount.hours": { en: "Hours", ar: "ساعات", es: "Horas", pt: "Horas", fr: "Heures", it: "Ore", de: "Stunden" },
  "discount.minutes": { en: "Minutes", ar: "دقائق", es: "Minutos", pt: "Minutos", fr: "Minutes", it: "Minuti", de: "Minuten" },
  "discount.seconds": { en: "Seconds", ar: "ثواني", es: "Segundos", pt: "Segundos", fr: "Secondes", it: "Secondi", de: "Sekunden" },
  "discount.min": { en: "Min", ar: "دق", es: "Min", pt: "Min", fr: "Min", it: "Min", de: "Min" },
  "discount.sec": { en: "Sec", ar: "ث", es: "Seg", pt: "Seg", fr: "Sec", it: "Sec", de: "Sek" },
  "discount.offerExpires": { en: "Offer expires in:", ar: "ينتهي العرض في:", es: "La oferta expira en:", pt: "A oferta expira em:", fr: "L'offre expire dans:", it: "L'offerta scade tra:", de: "Angebot läuft ab in:" },
  "discount.lockIn": { en: "Lock in 25% OFF before time runs out!", ar: "احصل على خصم 25% قبل انتهاء الوقت!", es: "¡Asegura tu 25% de descuento antes de que se acabe el tiempo!", pt: "Garanta seu 25% de desconto antes que o tempo acabe!", fr: "Obtenez 25% de réduction avant la fin du temps!", it: "Blocca il 25% di sconto prima che scada il tempo!", de: "Sichern Sie sich 25% Rabatt bevor die Zeit abläuft!" },

  // Case Studies
  "caseStudies.badge": { en: "Case Studies", ar: "دراسات الحالة", es: "Casos de Estudio", pt: "Estudos de Caso", fr: "Études de cas", it: "Casi di studio", de: "Fallstudien" },
  "caseStudies.title": { en: "Real Results for Real Businesses", ar: "نتائج حقيقية لأعمال حقيقية", es: "Resultados Reales para Negocios Reales", pt: "Resultados Reais para Negócios Reais", fr: "Des résultats réels pour de vraies entreprises", it: "Risultati reali per aziende reali", de: "Echte Ergebnisse für echte Unternehmen" },
  "caseStudies.subtitle": { en: "See how I've helped service businesses dominate their local markets and increase revenue through proven Local SEO strategies.", ar: "شاهد كيف ساعدت الشركات الخدمية على السيطرة على أسواقها المحلية وزيادة الإيرادات من خلال استراتيجيات SEO المحلية المثبتة.", es: "Vea cómo he ayudado a negocios de servicios a dominar sus mercados locales y aumentar ingresos a través de estrategias de SEO local comprobadas.", pt: "Veja como ajudei empresas de serviços a dominar seus mercados locais e aumentar a receita através de estratégias de SEO local comprovadas.", fr: "Découvrez comment j'ai aidé les entreprises de services à dominer leurs marchés locaux et à augmenter leurs revenus grâce à des stratégies de SEO local éprouvées.", it: "Scopri come ho aiutato le aziende di servizi a dominare i loro mercati locali e aumentare i ricavi attraverso strategie SEO locali comprovate.", de: "Sehen Sie, wie ich Service-Unternehmen geholfen habe, ihre lokalen Märkte zu dominieren und den Umsatz durch bewährte Local SEO Strategien zu steigern." },
  "caseStudies.challenge": { en: "Challenge", ar: "التحدي", es: "Desafío", pt: "Desafio", fr: "Défi", it: "Sfida", de: "Herausforderung" },
  "caseStudies.solution": { en: "Solution", ar: "الحل", es: "Solución", pt: "Solução", fr: "Solution", it: "Soluzione", de: "Lösung" },
  "caseStudies.results": { en: "Results", ar: "النتائج", es: "Resultados", pt: "Resultados", fr: "Résultats", it: "Risultati", de: "Ergebnisse" },
  "caseStudies.wantResults": { en: "Want Similar Results?", ar: "هل تريد نتائج مماثلة؟", es: "¿Quieres Resultados Similares?", pt: "Quer Resultados Semelhantes?", fr: "Vous voulez des résultats similaires?", it: "Vuoi risultati simili?", de: "Möchten Sie ähnliche Ergebnisse?" },
  "caseStudies.fullStack": { en: "Full-Stack Project", ar: "مشروع شامل", es: "Proyecto Full-Stack", pt: "Projeto Full-Stack", fr: "Projet Full-Stack", it: "Progetto Full-Stack", de: "Full-Stack Projekt" },

  // Certifications
  "cert.localSeo": { en: "Local SEO Certified", ar: "معتمد في SEO المحلي", es: "Certificado en SEO Local", pt: "Certificado em SEO Local", fr: "Certifié SEO local", it: "Certificato SEO locale", de: "Local SEO Zertifiziert" },
  "cert.hubspot": { en: "HubSpot SEO Certification", ar: "شهادة HubSpot SEO", es: "Certificación SEO de HubSpot", pt: "Certificação SEO da HubSpot", fr: "Certification SEO HubSpot", it: "Certificazione SEO HubSpot", de: "HubSpot SEO Zertifizierung" },
  "cert.projectMgmt": { en: "Project Management Certification", ar: "شهادة إدارة المشاريع", es: "Certificación en Gestión de Proyectos", pt: "Certificação em Gerenciamento de Projetos", fr: "Certification en gestion de projet", it: "Certificazione Project Management", de: "Projektmanagement Zertifizierung" },
  "cert.googleAnalytics": { en: "Google Analytics Certified", ar: "معتمد من Google Analytics", es: "Certificado de Google Analytics", pt: "Certificado do Google Analytics", fr: "Certifié Google Analytics", it: "Certificato Google Analytics", de: "Google Analytics Zertifiziert" },
  "cert.searchConsole": { en: "Google Search Console Certified", ar: "معتمد من Google Search Console", es: "Certificado de Google Search Console", pt: "Certificado do Google Search Console", fr: "Certifié Google Search Console", it: "Certificato Google Search Console", de: "Google Search Console Zertifiziert" },
  "cert.googleAds": { en: "Google Ads Search Certified", ar: "معتمد في إعلانات Google", es: "Certificado en Google Ads", pt: "Certificado em Google Ads", fr: "Certifié Google Ads", it: "Certificato Google Ads", de: "Google Ads Zertifiziert" },

  // Skills
  "skill.localSeo": { en: "Local SEO", ar: "SEO المحلي", es: "SEO Local", pt: "SEO Local", fr: "SEO local", it: "SEO locale", de: "Lokales SEO" },
  "skill.gbp": { en: "Google Business Profile", ar: "ملف Google التجاري", es: "Google Business Profile", pt: "Google Business Profile", fr: "Google Business Profile", it: "Google Business Profile", de: "Google Business Profile" },
  "skill.keywordResearch": { en: "Keyword Research", ar: "بحث الكلمات المفتاحية", es: "Investigación de Palabras Clave", pt: "Pesquisa de Palavras-chave", fr: "Recherche de mots-clés", it: "Ricerca parole chiave", de: "Keyword-Recherche" },
  "skill.onPage": { en: "On-Page SEO", ar: "SEO على الصفحة", es: "SEO On-Page", pt: "SEO On-Page", fr: "SEO On-Page", it: "SEO On-Page", de: "On-Page SEO" },
  "skill.technical": { en: "Technical SEO", ar: "SEO التقني", es: "SEO Técnico", pt: "SEO Técnico", fr: "SEO technique", it: "SEO tecnico", de: "Technisches SEO" },
  "skill.content": { en: "Content Strategy", ar: "استراتيجية المحتوى", es: "Estrategia de Contenido", pt: "Estratégia de Conteúdo", fr: "Stratégie de contenu", it: "Strategia di contenuto", de: "Content-Strategie" },
  "skill.linkBuilding": { en: "Link Building", ar: "بناء الروابط", es: "Link Building", pt: "Link Building", fr: "Link Building", it: "Link Building", de: "Linkaufbau" },
  "skill.citation": { en: "Citation Management", ar: "إدارة الاستشهادات", es: "Gestión de Citaciones", pt: "Gerenciamento de Citações", fr: "Gestion des citations", it: "Gestione citazioni", de: "Zitatverwaltung" },
  "skill.conversion": { en: "Conversion Optimization", ar: "تحسين التحويل", es: "Optimización de Conversión", pt: "Otimização de Conversão", fr: "Optimisation de conversion", it: "Ottimizzazione conversione", de: "Conversion-Optimierung" },
  "skill.analytics": { en: "Analytics & Reporting", ar: "التحليلات والتقارير", es: "Analytics y Reportes", pt: "Analytics e Relatórios", fr: "Analytics et rapports", it: "Analytics e reportistica", de: "Analytics & Reporting" },
  "skill.projectMgmt": { en: "Project Management", ar: "إدارة المشاريع", es: "Gestión de Proyectos", pt: "Gerenciamento de Projetos", fr: "Gestion de projet", it: "Gestione progetti", de: "Projektmanagement" },
  "skill.clientComm": { en: "Client Communication", ar: "التواصل مع العملاء", es: "Comunicación con Clientes", pt: "Comunicação com Clientes", fr: "Communication client", it: "Comunicazione clienti", de: "Kundenkommunikation" },
  "skill.teamCollab": { en: "Team Collaboration", ar: "التعاون الجماعي", es: "Colaboración en Equipo", pt: "Colaboração em Equipe", fr: "Collaboration d'équipe", it: "Collaborazione di squadra", de: "Teamzusammenarbeit" },
  "skill.strategic": { en: "Strategic Planning", ar: "التخطيط الاستراتيجي", es: "Planificación Estratégica", pt: "Planejamento Estratégico", fr: "Planification stratégique", it: "Pianificazione strategica", de: "Strategische Planung" },
  "skill.performance": { en: "Performance Tracking", ar: "تتبع الأداء", es: "Seguimiento de Rendimiento", pt: "Rastreamento de Desempenho", fr: "Suivi des performances", it: "Tracciamento prestazioni", de: "Performance-Tracking" },

  // Contact labels
  "contact.email.label": { en: "Email", ar: "البريد الإلكتروني", es: "Correo", pt: "E-mail", fr: "E-mail", it: "Email", de: "E-Mail" },
  "contact.whatsapp.label": { en: "WhatsApp", ar: "واتساب", es: "WhatsApp", pt: "WhatsApp", fr: "WhatsApp", it: "WhatsApp", de: "WhatsApp" },

  // Testimonial quotes (sample for AI translation fallback) 
  "testimonial.quote1": { en: "Hadi transformed our Google Business Profile and now we receive daily calls from Google Maps. His local SEO knowledge is exceptional.", ar: "غيّر هادي ملف Google Business الخاص بنا والآن نتلقى مكالمات يومية من خرائط Google. معرفته بـ SEO المحلي استثنائية.", es: "Hadi transformó nuestro perfil de Google Business y ahora recibimos llamadas diarias desde Google Maps. Su conocimiento de SEO local es excepcional.", pt: "Hadi transformou nosso perfil do Google Business e agora recebemos chamadas diárias do Google Maps. Seu conhecimento de SEO local é excepcional.", fr: "Hadi a transformé notre profil Google Business et maintenant nous recevons des appels quotidiens depuis Google Maps. Sa connaissance du SEO local est exceptionnelle.", it: "Hadi ha trasformato il nostro profilo Google Business e ora riceviamo chiamate giornaliere da Google Maps. La sua conoscenza del SEO locale è eccezionale.", de: "Hadi hat unser Google Business Profil transformiert und jetzt erhalten wir täglich Anrufe von Google Maps. Sein Wissen über lokales SEO ist außergewöhnlich." },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const DYNAMIC_STORAGE_PREFIX = "dynamicTranslations.v1.";

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      const stored = localStorage.getItem("language") as Language;
      if (stored && ["en", "ar", "es", "pt", "fr", "it", "de"].includes(stored)) return stored;

      // Detect browser language
      const browserLang = navigator.language.slice(0, 2);
      if (browserLang === "ar") return "ar";
      if (browserLang === "es") return "es";
      if (browserLang === "pt") return "pt";
      if (browserLang === "fr") return "fr";
      if (browserLang === "it") return "it";
      if (browserLang === "de") return "de";
    }
    return "en";
  });

  const [dynamicTranslations, setDynamicTranslations] = useState<Record<string, string>>({});
  const pendingRef = useRef<Set<string>>(new Set());
  const [pendingTick, setPendingTick] = useState(0);

  useEffect(() => {
    localStorage.setItem("language", language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
  }, [language]);

  useEffect(() => {
    // Load per-language cached dynamic translations (AI translated)
    if (typeof window === "undefined") return;

    pendingRef.current.clear();

    if (language === "en") {
      setDynamicTranslations({});
      return;
    }

    const raw = localStorage.getItem(`${DYNAMIC_STORAGE_PREFIX}${language}`);
    if (!raw) {
      setDynamicTranslations({});
      return;
    }

    try {
      const parsed = JSON.parse(raw);
      if (parsed && typeof parsed === "object") setDynamicTranslations(parsed);
      else setDynamicTranslations({});
    } catch {
      setDynamicTranslations({});
    }
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = useMemo(() => {
    return (key: string): string => {
      const staticTranslation = translations[key];
      if (staticTranslation) return staticTranslation[language] || staticTranslation.en || key;

      // If it's a missing translation KEY (e.g. "pricing.foo"), don't send it to AI.
      if (key.includes(".")) return key;

      // For English we just render the input string.
      if (language === "en") return key;

      // Dynamic AI translation cache
      const cached = dynamicTranslations[key];
      if (cached) return cached;

      // Enqueue for translation (batched)
      if (!pendingRef.current.has(key)) {
        pendingRef.current.add(key);
        setPendingTick((x) => x + 1);
      }

      // Show English until translation arrives
      return key;
    };
  }, [dynamicTranslations, language]);

  useEffect(() => {
    if (language === "en") return;
    if (pendingRef.current.size === 0) return;

    const handle = window.setTimeout(async () => {
      const batch = Array.from(pendingRef.current).slice(0, 40);
      if (batch.length === 0) return;

      const { data, error } = await supabase.functions.invoke("translate", {
        body: { targetLanguage: language, texts: batch },
      });

      // Always remove processed items from the queue (avoid infinite loops on errors)
      batch.forEach((txt) => pendingRef.current.delete(txt));

      if (error || !data?.translations) {
        // Try again later if there are still items in the queue
        if (pendingRef.current.size > 0) setPendingTick((x) => x + 1);
        return;
      }

      setDynamicTranslations((prev) => {
        const next = { ...prev, ...data.translations };
        try {
          localStorage.setItem(`${DYNAMIC_STORAGE_PREFIX}${language}`, JSON.stringify(next));
        } catch {
          // ignore quota issues
        }
        return next;
      });

      if (pendingRef.current.size > 0) setPendingTick((x) => x + 1);
    }, 250);

    return () => window.clearTimeout(handle);
  }, [language, pendingTick]);

  const dir = language === "ar" ? "rtl" : "ltr";

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

